version: 0.0
os: linux
files:
  - source: /UI/FrontEndv8/dist
    destination: //opt/tomcat/webapps/uprn-match
  - source: /UI/API/target/API-0.0.1
    destination: //opt/tomcat/webapps/uprn-match
hooks:
  BeforeInstall:
    - location: UI/aws_scripts/cleanup
      timeout: 300
      runas: root
