version: 0.0
os: linux
files:
  - source: /dist
    destination: //opt/tomcat/webapps/uprn-match
  - source: /dist
    destination: //opt/tomcat/webapps/uprn-match
hooks:
  BeforeInstall:
    - location: aws_script/cleanup
      timeout: 300
      runas: root
